export const SUPPORT_PHONE_TEL = '+12139659727';
export const SUPPORT_PHONE_DISPLAY = '+1 (213) 965-9727';
export const SUPPORT_PHONE_HREF = `tel:${SUPPORT_PHONE_TEL}`;

export const BUSINESS_ADDRESS_STREET = '1309 Coffeen Avenue STE 1200';
export const BUSINESS_ADDRESS_CITY = 'Sheridan';
export const BUSINESS_ADDRESS_STATE = 'Wyoming';
export const BUSINESS_ADDRESS_STATE_CODE = 'WY';
export const BUSINESS_ADDRESS_ZIP = '82801';
export const BUSINESS_ADDRESS_FULL = `${BUSINESS_ADDRESS_STREET}, ${BUSINESS_ADDRESS_CITY}, ${BUSINESS_ADDRESS_STATE} ${BUSINESS_ADDRESS_ZIP} US`;
export const BUSINESS_ADDRESS_SHORT = `${BUSINESS_ADDRESS_STREET}, ${BUSINESS_ADDRESS_CITY}, ${BUSINESS_ADDRESS_STATE_CODE} ${BUSINESS_ADDRESS_ZIP}`;

